// Copyright AGNTCY Contributors (https://github.com/agntcy)
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: core/v1/record.proto

package corev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	RecordObjectManager_ConvertObjectToRecord_FullMethodName = "/core.v1.RecordObjectManager/ConvertObjectToRecord"
	RecordObjectManager_ConvertRecordToObject_FullMethodName = "/core.v1.RecordObjectManager/ConvertRecordToObject"
)

// RecordObjectManagerClient is the client API for RecordObjectManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Converts Object to a RecordObject and vice versa.
// This is client-side service only.
type RecordObjectManagerClient interface {
	// Converts an Object to a Record.
	ConvertObjectToRecord(ctx context.Context, in *Object, opts ...grpc.CallOption) (*RecordObject, error)
	// Converts a Record to an Object.
	ConvertRecordToObject(ctx context.Context, in *RecordObject, opts ...grpc.CallOption) (*Object, error)
}

type recordObjectManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordObjectManagerClient(cc grpc.ClientConnInterface) RecordObjectManagerClient {
	return &recordObjectManagerClient{cc}
}

func (c *recordObjectManagerClient) ConvertObjectToRecord(ctx context.Context, in *Object, opts ...grpc.CallOption) (*RecordObject, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordObject)
	err := c.cc.Invoke(ctx, RecordObjectManager_ConvertObjectToRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordObjectManagerClient) ConvertRecordToObject(ctx context.Context, in *RecordObject, opts ...grpc.CallOption) (*Object, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Object)
	err := c.cc.Invoke(ctx, RecordObjectManager_ConvertRecordToObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordObjectManagerServer is the server API for RecordObjectManager service.
// All implementations should embed UnimplementedRecordObjectManagerServer
// for forward compatibility.
//
// Converts Object to a RecordObject and vice versa.
// This is client-side service only.
type RecordObjectManagerServer interface {
	// Converts an Object to a Record.
	ConvertObjectToRecord(context.Context, *Object) (*RecordObject, error)
	// Converts a Record to an Object.
	ConvertRecordToObject(context.Context, *RecordObject) (*Object, error)
}

// UnimplementedRecordObjectManagerServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecordObjectManagerServer struct{}

func (UnimplementedRecordObjectManagerServer) ConvertObjectToRecord(context.Context, *Object) (*RecordObject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertObjectToRecord not implemented")
}
func (UnimplementedRecordObjectManagerServer) ConvertRecordToObject(context.Context, *RecordObject) (*Object, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConvertRecordToObject not implemented")
}
func (UnimplementedRecordObjectManagerServer) testEmbeddedByValue() {}

// UnsafeRecordObjectManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordObjectManagerServer will
// result in compilation errors.
type UnsafeRecordObjectManagerServer interface {
	mustEmbedUnimplementedRecordObjectManagerServer()
}

func RegisterRecordObjectManagerServer(s grpc.ServiceRegistrar, srv RecordObjectManagerServer) {
	// If the following call pancis, it indicates UnimplementedRecordObjectManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecordObjectManager_ServiceDesc, srv)
}

func _RecordObjectManager_ConvertObjectToRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Object)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordObjectManagerServer).ConvertObjectToRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordObjectManager_ConvertObjectToRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordObjectManagerServer).ConvertObjectToRecord(ctx, req.(*Object))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordObjectManager_ConvertRecordToObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordObjectManagerServer).ConvertRecordToObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecordObjectManager_ConvertRecordToObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordObjectManagerServer).ConvertRecordToObject(ctx, req.(*RecordObject))
	}
	return interceptor(ctx, in, info, handler)
}

// RecordObjectManager_ServiceDesc is the grpc.ServiceDesc for RecordObjectManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordObjectManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.v1.RecordObjectManager",
	HandlerType: (*RecordObjectManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConvertObjectToRecord",
			Handler:    _RecordObjectManager_ConvertObjectToRecord_Handler,
		},
		{
			MethodName: "ConvertRecordToObject",
			Handler:    _RecordObjectManager_ConvertRecordToObject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/v1/record.proto",
}
