# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/v1/object.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'core/v1/object.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63ore/v1/object.proto\x12\x07\x63ore.v1\"\x1d\n\tObjectRef\x12\x10\n\x03\x63id\x18\x01 \x01(\tR\x03\x63id\"\x9c\x02\n\x06Object\x12\x10\n\x03\x63id\x18\x01 \x01(\tR\x03\x63id\x12\'\n\x04type\x18\x02 \x01(\x0e\x32\x13.core.v1.ObjectTypeR\x04type\x12\x42\n\x0b\x61nnotations\x18\x03 \x03(\x0b\x32 .core.v1.Object.AnnotationsEntryR\x0b\x61nnotations\x12\x1d\n\ncreated_at\x18\x04 \x01(\tR\tcreatedAt\x12\x12\n\x04size\x18\x05 \x01(\x04R\x04size\x12\x17\n\x04\x64\x61ta\x18\x06 \x01(\x0cH\x00R\x04\x64\x61ta\x88\x01\x01\x1a>\n\x10\x41nnotationsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x42\x07\n\x05_data*F\n\nObjectType\x12\x1b\n\x17OBJECT_TYPE_UNSPECIFIED\x10\x00\x12\x13\n\x0fOBJECT_TYPE_RAW\x10\x01\"\x06\x08\xe8\x07\x10\x8fNB\x81\x01\n\x0b\x63om.core.v1B\x0bObjectProtoP\x01Z(github.com/agntcy/dir/api/core/v1;corev1\xa2\x02\x03\x43XX\xaa\x02\x07\x43ore.V1\xca\x02\x07\x43ore\\V1\xe2\x02\x13\x43ore\\V1\\GPBMetadata\xea\x02\x08\x43ore::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.v1.object_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.core.v1B\013ObjectProtoP\001Z(github.com/agntcy/dir/api/core/v1;corev1\242\002\003CXX\252\002\007Core.V1\312\002\007Core\\V1\342\002\023Core\\V1\\GPBMetadata\352\002\010Core::V1'
  _globals['_OBJECT_ANNOTATIONSENTRY']._loaded_options = None
  _globals['_OBJECT_ANNOTATIONSENTRY']._serialized_options = b'8\001'
  _globals['_OBJECTTYPE']._serialized_start=351
  _globals['_OBJECTTYPE']._serialized_end=421
  _globals['_OBJECTREF']._serialized_start=33
  _globals['_OBJECTREF']._serialized_end=62
  _globals['_OBJECT']._serialized_start=65
  _globals['_OBJECT']._serialized_end=349
  _globals['_OBJECT_ANNOTATIONSENTRY']._serialized_start=278
  _globals['_OBJECT_ANNOTATIONSENTRY']._serialized_end=340
# @@protoc_insertion_point(module_scope)
