# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core/v1/record.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'core/v1/record.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oasf.v1alpha1 import agent_pb2 as oasf_dot_v1alpha1_dot_agent__pb2
from oasf.v1alpha2 import record_pb2 as oasf_dot_v1alpha2_dot_record__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63ore/v1/record.proto\x12\x07\x63ore.v1\x1a\x19oasf/v1alpha1/agent.proto\x1a\x1aoasf/v1alpha2/record.proto\"\x1d\n\tRecordRef\x12\x10\n\x03\x63id\x18\x01 \x01(\tR\x03\x63id\"\xec\x01\n\nRecordMeta\x12\x10\n\x03\x63id\x18\x01 \x01(\tR\x03\x63id\x12\x46\n\x0b\x61nnotations\x18\x02 \x03(\x0b\x32$.core.v1.RecordMeta.AnnotationsEntryR\x0b\x61nnotations\x12%\n\x0eschema_version\x18\x03 \x01(\tR\rschemaVersion\x12\x1d\n\ncreated_at\x18\x04 \x01(\tR\tcreatedAt\x1a>\n\x10\x41nnotationsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"y\n\x06Record\x12\x32\n\x08v1alpha1\x18\x01 \x01(\x0b\x32\x14.oasf.v1alpha1.AgentH\x00R\x08v1alpha1\x12\x33\n\x08v1alpha2\x18\x02 \x01(\x0b\x32\x15.oasf.v1alpha2.RecordH\x00R\x08v1alpha2B\x06\n\x04\x64\x61taB\x81\x01\n\x0b\x63om.core.v1B\x0bRecordProtoP\x01Z(github.com/agntcy/dir/api/core/v1;corev1\xa2\x02\x03\x43XX\xaa\x02\x07\x43ore.V1\xca\x02\x07\x43ore\\V1\xe2\x02\x13\x43ore\\V1\\GPBMetadata\xea\x02\x08\x43ore::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core.v1.record_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.core.v1B\013RecordProtoP\001Z(github.com/agntcy/dir/api/core/v1;corev1\242\002\003CXX\252\002\007Core.V1\312\002\007Core\\V1\342\002\023Core\\V1\\GPBMetadata\352\002\010Core::V1'
  _globals['_RECORDMETA_ANNOTATIONSENTRY']._loaded_options = None
  _globals['_RECORDMETA_ANNOTATIONSENTRY']._serialized_options = b'8\001'
  _globals['_RECORDREF']._serialized_start=88
  _globals['_RECORDREF']._serialized_end=117
  _globals['_RECORDMETA']._serialized_start=120
  _globals['_RECORDMETA']._serialized_end=356
  _globals['_RECORDMETA_ANNOTATIONSENTRY']._serialized_start=294
  _globals['_RECORDMETA_ANNOTATIONSENTRY']._serialized_end=356
  _globals['_RECORD']._serialized_start=358
  _globals['_RECORD']._serialized_end=479
# @@protoc_insertion_point(module_scope)
