# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: store/v1alpha1/object.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'store/v1alpha1/object.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from oasf.v1alpha1 import agent_pb2 as oasf_dot_v1alpha1_dot_agent__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bstore/v1alpha1/object.proto\x12\x0estore.v1alpha1\x1a\x19oasf/v1alpha1/agent.proto\"\xd9\x01\n\tObjectRef\x12\x16\n\x06\x64igest\x18\x01 \x01(\tR\x06\x64igest\x12\x12\n\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n\x04size\x18\x03 \x01(\x04R\x04size\x12L\n\x0b\x61nnotations\x18\x04 \x03(\x0b\x32*.store.v1alpha1.ObjectRef.AnnotationsEntryR\x0b\x61nnotations\x1a>\n\x10\x41nnotationsEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\"\x91\x01\n\x06Object\x12\x12\n\x04\x64\x61ta\x18\x01 \x01(\x0cR\x04\x64\x61ta\x12\x30\n\x03ref\x18\x02 \x01(\x0b\x32\x19.store.v1alpha1.ObjectRefH\x00R\x03ref\x88\x01\x01\x12/\n\x05\x61gent\x18\x03 \x01(\x0b\x32\x14.oasf.v1alpha1.AgentH\x01R\x05\x61gent\x88\x01\x01\x42\x06\n\x04_refB\x08\n\x06_agent*8\n\nObjectType\x12\x13\n\x0fOBJECT_TYPE_RAW\x10\x00\x12\x15\n\x11OBJECT_TYPE_AGENT\x10\x01\x42\xb2\x01\n\x12\x63om.store.v1alpha1B\x0bObjectProtoP\x01Z6github.com/agntcy/dir/api/store/v1alpha1;storev1alpha1\xa2\x02\x03SXX\xaa\x02\x0eStore.V1alpha1\xca\x02\x0eStore\\V1alpha1\xe2\x02\x1aStore\\V1alpha1\\GPBMetadata\xea\x02\x0fStore::V1alpha1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'store.v1alpha1.object_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.store.v1alpha1B\013ObjectProtoP\001Z6github.com/agntcy/dir/api/store/v1alpha1;storev1alpha1\242\002\003SXX\252\002\016Store.V1alpha1\312\002\016Store\\V1alpha1\342\002\032Store\\V1alpha1\\GPBMetadata\352\002\017Store::V1alpha1'
  _globals['_OBJECTREF_ANNOTATIONSENTRY']._loaded_options = None
  _globals['_OBJECTREF_ANNOTATIONSENTRY']._serialized_options = b'8\001'
  _globals['_OBJECTTYPE']._serialized_start=442
  _globals['_OBJECTTYPE']._serialized_end=498
  _globals['_OBJECTREF']._serialized_start=75
  _globals['_OBJECTREF']._serialized_end=292
  _globals['_OBJECTREF_ANNOTATIONSENTRY']._serialized_start=230
  _globals['_OBJECTREF_ANNOTATIONSENTRY']._serialized_end=292
  _globals['_OBJECT']._serialized_start=295
  _globals['_OBJECT']._serialized_end=440
# @@protoc_insertion_point(module_scope)
